- request:
    url: "/hotel/get-hotels"
    method: GET
  response:
    status: 200
    latency: 5000
    headers:
      content-type: application/json
    file: "response/hotel/getHotels/response.json"